### ISSUE TITLE
checkForExpiry can cause processes to panic

### ISSUE THREAD

**Issue by quadtrix** [quadtrix/basicqueue#1]
panic: runtime error: index out of range [0] with length 0

goroutine 9 [running]:
github.com/quadtrix/basicqueue.(*BasicQueue).checkForExpiry(0xc000144100)
	/home/nhtbrink/go/pkg/mod/github.com/quadtrix/basicqueue@v0.0.0-20230802091001-7442fc831ebe/basicqueue.go:382 +0x178
github.com/quadtrix/basicqueue.(*BasicQueue).loopExpiryCheck(0xc000144100)
	/home/nhtbrink/go/pkg/mod/github.com/quadtrix/basicqueue@v0.0.0-20230802091001-7442fc831ebe/basicqueue.go:373 +0x213
created by github.com/quadtrix/basicqueue.NewQueue
	/home/nhtbrink/go/pkg/mod/github.com/quadtrix/basicqueue@v0.0.0-20230802091001-7442fc831ebe/basicqueue.go:170 +0x305

**Comment by quadtrix** [comment]
Redesign of the queue locking mechanism.
